### PR TITLE
Java 2D Example

### PR DESCRIPTION
**Pull request by randomcmd**
Adding DVD Logo Simulator using Java 2D with IntelliJ

### CODE REVIEW

**Comment by dkantereivin** [comment]
Thanks for your proposal!

Given the nature of your project, I would strongly request and appreciate some guidance in the README and within your code comments:
1. To what sorts of projects is this work a helpful example.
2. Explanation of how and why you implemented certain parts of your code, so that it may be more understandable to others.

Additionally, please complete the following so we can merge your PR:

- [x] README.md
- [x] Add `.idea/` to your `.gitignore`, then run `git rm .idea/` and then recommit. These are editor specific files, and not related to your project example.
- [x] Provide more descriptive commit messages, so that this repository will be a good example to others of how to utilize version control systems such as Git. Before you make any changes or add more commits, I strongly suggest changing the most recent commit message (81c2d72) to something more, uh, descriptive. To do this, you'll take an unchanged version of your project, run `git commit --amend -m "put your new message here"` and then `git push origin master --force` (assuming that randomcmd:master) is configured remote `origin`).
- [x] Change Pull Request Title
- [ ] Add a proper description to your pull request, just using the edit feature on GH.

Happy to help you make these changes if needed - thanks for helping to keep the quality of code on our example repository top notch! Just comment here once you've completed the above!

**Comment by randomcmd** [comment]
Thanks for your reply! I believe to have fixed all of the things now

**Review by dkantereivin — CHANGES_REQUESTED** [review]
This is not the correct course of action. Do not delete this `.gitignore`, instead you'll want to restore the original version with `out/` and simply add a line for all the folders you want to ignore, such as `.idea`.

This is needed so that once you run `git rm .idea/` it doesn't add it back.

**Review by dkantereivin — COMMENTED** [review]
This is fine if you want to do it this way, however I'd suggest using `.md` and you can see the benefits of using this format and including some extra detail. Completely up to you, so for right now, I'm going to mark this step done but feel free to change it. https://raw.githubusercontent.com/dkantereivin/programmers-palace-examples/master/discord-mass-role-giver/README.md

**Comment by dkantereivin** [comment]
Ready for review.

**Review by Forbidden-A — APPROVED** [review]
It'd be better if you explained some of the code or smth and added comments but its good enough I guess.

**Comment by dkantereivin** [comment]
Whatever, I think this is acceptable enough to merge. Definitely worth a quality improvement PR if you're up for it down the line.

**Pull request merged**
