### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CharlieS1103**
it is basically a terminal-based project that allows the user to define how many students they want to configure, set the first and last name for each student, give the student a random student id, set and keep track of the student's balance and tuition, and configure what courses the student is taken. I basically made it since a lot of people in the #java channel seem to be having trouble with the same thing.

### CODE REVIEW

**Comment by dkantereivin** [comment]
Because this is fairly simple and it's not immediately apparent what this code does, please add a README.md file which outlines authorship, purpose, functionality, and methods. Include any relevant context that the program was written in.

Please also rename to student-managment (just the parent folder).

**Comment by reginsmol** [comment]
This was somewhat difficult to read because of the lack of consistent formatting.

**Comment by dkantereivin** [comment]
@SaltNuggets sorry about taking so long to review this PR. Could you please do the following:
1. Rename the top level folder to `student-management` to follow consistent styling with the project. If the project cannot be easily renamed, feel free to nest your current code within a folder.

2. Fix the formatting within your source code (`.java`) files manually, or using an auto-formatter. Simply follow standard 4-space indentation rules (or if you strongly prefer, 2 spaces is acceptable).

3. Create a `.gitignore` file in the root directory (of the repo) which ignores `.class` files.

See above comments from myself and @reginsmol. Thank you!

**Comment by dkantereivin** [comment]
Closed due to inactivity.

**Pull request closed without merging**
